// laod enviroment variables from .env file...
import dotenv from 'dotenv';
dotenv.config();

// import necessary modules...
import express from 'express';
import cors from 'cors';

// create an instance of Express...
const app = express();
const PORT = process.env.PORT;

// middleware configuration...
app.use(cors()); // emable cors for all routes...
app.use(express.json()); // parse incoming json requests...

// associate the router with the root('/') path of the application...
//app.use('/', router)

// start the server...
app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server is listening at http://localhost:${PORT}`);
});